development:
  adapter: postgresql
  encoding: unicode
  database: third-app-development
  pool: 5
  username: zabdi

test:
  adapter: postgresql
  encoding: unicode
  database: third-app-test
  pool: 5
  username: zabdi

production:
  adapter: postgresql
  encoding: utf8
  database: third-app-production
  pool: 5
  username: third-app
  password: password123
  socket: /tmp/mysql.sock
